#-------------------------------
# General Site Settings

title: Danielle Gilman UX Portfolio
logo: 
author: danusha
description: Danielle Gilman's UX Design Portfolio
email: danusha@gmail.com
current-employer: Nasdaq
location: Atlanta, GA
copyright: Copyright &copy; 2022 Designed by [Danielle Gilman](https://daniellegilman.com) & Developed by [Justin Gilman](https://eyeofmidas.com)

menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi, I'm Danielle Gilman
  hero-subtext: UX Designer currently working with Nasdaq on eVestment Analytics.<br />Based in Atlanta 🍑 GA
social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/daniellegilman/"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  <p>I'm a UX designer based in Atlanta, GA. I currently focus on web applications, but in my free time I work on video games. </p>
  <p>I have a degree from Georgia Tech in Computational Media and have worked with digital media companies across the US.</p>
  <p>Feel free to drop me a line if you have a project you want to discuss or even chat about your favorite video game!</p>

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Design, color: '#fdb157', value: '60%'}
- {name: Figma, color: '#9473e6', value: '90%'}
- {name: UX Principles, color: '#bdecf6', value: '80%'}
- {name: Gamification, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: UX Designer, icon: 'icon-1.png', date: 'Jun 2021 - Current', organization: 'NASDAQ'}
- {name: UX Designer, icon: 'icon-2.png', date: 'Jun 2016 - Jan 2020', organization: 'COPPERWIRE'}
- {name: UX Designer, icon: 'icon-3.png', date: 'Jan 2016 - May 2016', organization: 'NUTRIO'}
- {name: UX Designer, icon: 'icon-1.png', date: 'Apr 2010 - Jun 2010', organization: 'PINNACLEPROMOTIONS'}
- {name: UX Intern, icon: 'icon-2.png', date: '2010', organization: 'HIREZ'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Bachelors of Science in Computational Media, date: '2010', organization: 'Georgia Institute of Technology'}

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    title: "Example"
    description: "A small portfolio example"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    title: "Example"
    description: "A small portfolio example"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    title: "Example"
    description: "A small portfolio example"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    title: "Example"
    description: "A small portfolio example"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    title: "Example"
    description: "A small portfolio example"

  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    title: "Example"
    description: "A small portfolio example"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "Gamification",
    type : "gamification"
  }
- {
    title : "Process",
    type : "process"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "gamification"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "process"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "gamification"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "gamification"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "process"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "gamification"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "process"
      - type: "gamification"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "process"


#-------------------------------
# Contact Section

contact-title: Contact Info
